global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'test-postgres'
    metrics_path: /pg-exporter/metrics
    static_configs:
      - targets: ['srv-020.devops.ls.eee.intern']

  - job_name: 'prod-postgres'
    metrics_path: /pg-exporter/metrics
    static_configs:
      - targets: ['srv-021.devops.ls.eee.intern']

  - job_name: 'frontend-http'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - http://srv-020.devops.ls.eee.intern/
        labels:
          env: test
      - targets:
          - http://srv-021.devops.ls.eee.intern/
        labels:
          env: prod
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'backend-http'
    metrics_path: /probe
    params:
      module: [ http_2xx ]
    static_configs:
      - targets:
          - http://srv-020.devops.ls.eee.intern/api
        labels:
          env: test
      - targets:
          - http://srv-021.devops.ls.eee.intern/api
        labels:
          env: prod
    relabel_configs:
      - source_labels: [ __address__ ]
        target_label: __param_target
      - source_labels: [ __param_target ]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
