micronaut.application.name=g01-form-backend
micronaut.server.host=0.0.0.0
micronaut.server.port=8080
micronaut.server.context-path=/api
micronaut.router.static-resources.swagger.paths=classpath\:META-INF/swagger
micronaut.router.static-resources.swagger-ui.mapping=/swagger-ui/**
micronaut.router.static-resources.swagger-ui.paths=classpath\:META-INF/swagger/views/swagger-ui
micronaut.router.static-resources.swagger.mapping=/swagger/**
datasources.default.driver-class-name=org.postgresql.Driver
datasources.default.dialect=POSTGRES
datasources.default.url=${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
datasources.default.username=${POSTGRES_USER:`postgres`}
datasources.default.password=${POSTGRES_PASSWORD:`postgres`}
datasources.default.schema-generate=NONE
flyway.datasources.default.enabled=true
flyway.datasources.default.locations=classpath:db/migration
unleash.url=${UNLEASH_URL:`https://gitlab.com/api/v4/feature_flags/unleash/`}
unleash.instance-id=${UNLEASH_INSTANCE_ID:instance_id}
unleash.app-name=${UNLEASH_APP_NAME:g01-form-backend}
unleash.environment=${UNLEASH_ENVIRONMENT:dev}
unleash.fetch-interval=${UNLEASH_FETCH_INTERVAL:1}