micronaut.server.cors.enabled=true
micronaut.server.cors.configurations.all.allowed-origins=http://localhost:3000,http://localhost:5173
micronaut.server.cors.configurations.all.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
micronaut.server.cors.configurations.all.allowed-headers=Origin,Content-Type,Accept,Authorization
datasources.default.url=${JDBC_URL:`jdbc:postgresql://localhost:5432/postgres`}
datasources.default.username=${DB_USER:`postgres`}
datasources.default.password=${DB_PASS:`postgres`}
datasources.default.schema-generate: CREATE-DROP
